services:
  wonderwall-dev-gcp:
    container_name: wonderwall-dev-gcp
    image: ghcr.io/nais/wonderwall:latest
    restart: on-failure
    ports:
      - "4000:4000"
    command: --openid.provider azure
    environment:
      WONDERWALL_INGRESS: http://localhost:4000
      WONDERWALL_BIND_ADDRESS: 0.0.0.0:4000
      WONDERWALL_UPSTREAM_HOST: host.docker.internal:3000
      WONDERWALL_AUTO_LOGIN: true
      WONDERWALL_LOG_FORMAT: text
    env_file:
      - .env.dev-gcp # Opprettes med script get-secret.sh. Les README
